spring:
  application:
    name: api-parking-lot
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:parkin_lot;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

server:
  port: 8080

logging:
  level:
    root: INFO